[package]
name = "cbot-rs"
version = "0.1.0"
license = "GPL-3.0-or-later"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "cbot"
path = "src/lib.rs"

[dependencies]
reqwest = "0.9"
soup = "0.5"
